### ISSUE TITLE
Does not support split apks

### ISSUE THREAD

**Issue by wilco375** [ikolomiko/gplay-downloader#2]
When downloading a split application like com.adobe.reader, only the main binary is downloaded, and the required additional apks are ignored. 

Can be relatively easily fixed by changing Downloader.kt to download all apks instead of just the one that the package name matches (https://github.com/ikolomiko/gplay-downloader/blob/0f5fa4a09047c3bc4547879b398bd0d631f03967/app/src/main/kotlin/gplay/downloader/Downloader.kt#L32)

**Comment by ikolomiko** [comment]
The code was intentional since I only needed the main binary, but I can see the use cases where one might need other APKs. I will add a command line option for this feature soon!
